services:
  auth-db:
    image: postgres:15
    container_name: auth-db
    restart: always
    volumes:
      - auth-db-data:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: kanban_user
      POSTGRES_PASSWORD: kanban_pass
      POSTGRES_DB: authdb
      POSTGRES_MULTIPLE_DATABASES: authdb,test_authdb
    ports:
      - "5432:5432"

  auth:
    build:
      context: ./services/auth
    container_name: auth-service
    depends_on:
      - auth-db
    environment:
      ENV: docker
      POSTGRES_USER: kanban_user
      POSTGRES_PASSWORD: kanban_pass
      POSTGRES_DB: authdb
    env_file:
      - ./services/auth/.env.docker
    volumes:
      - ./services/auth:/app
    ports:
      - "8000:8000"
    command: ["/bin/bash", "/start.sh"]

volumes:
  auth-db-data:
