global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'auth-service'
    metrics_path: /metrics
    static_configs:
      - targets: ['auth:8000']
  - job_name: 'board-service'
    metrics_path: /metrics
    static_configs:
      - targets: ['board:3000']